// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'text!templates/list-visits.html'], function(_, Backbone, tmpl) {
    var ListVisitsView;
    ListVisitsView = (function(_super) {

      __extends(ListVisitsView, _super);

      function ListVisitsView() {
        this.render = __bind(this.render, this);
        return ListVisitsView.__super__.constructor.apply(this, arguments);
      }

      ListVisitsView.prototype.el = '#page-list-visits';

      ListVisitsView.prototype.template = _.template(tmpl);

      ListVisitsView.prototype.render = function() {
        $(this.el).html(this.template());
        return this;
      };

      return ListVisitsView;

    })(Backbone.View);
    return ListVisitsView;
  });

}).call(this);
