// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'jqueryUiMap', 'text!templates/map.html'], function(_, Backbone, JQMap, tmpl) {
    var MapView;
    MapView = (function(_super) {

      __extends(MapView, _super);

      function MapView() {
        this.render = __bind(this.render, this);
        return MapView.__super__.constructor.apply(this, arguments);
      }

      MapView.prototype.el = '#page-map';

      MapView.prototype.template = _.template(tmpl);

      MapView.prototype.render = function() {
        $(this.el).html(this.template());
        this.$el.find("#map").gmap();
        return this;
      };

      return MapView;

    })(Backbone.View);
    return MapView;
  });

}).call(this);
