// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'text!templates/visits-page.html', "../views/ListVisitsView"], function(_, Backbone, tmpl, ListVisitsView) {
    var ListVisitsPageView;
    ListVisitsPageView = (function(_super) {

      __extends(ListVisitsPageView, _super);

      function ListVisitsPageView() {
        this.loadVisits = __bind(this.loadVisits, this);

        this.render = __bind(this.render, this);

        this.initialize = __bind(this.initialize, this);
        return ListVisitsPageView.__super__.constructor.apply(this, arguments);
      }

      ListVisitsPageView.prototype.el = '#page-list-visits';

      ListVisitsPageView.prototype.template = _.template(tmpl);

      ListVisitsPageView.prototype.initialize = function() {
        return _.bindAll(this);
      };

      ListVisitsPageView.prototype.render = function() {
        $(this.el).html(this.template());
        return this;
      };

      ListVisitsPageView.prototype.loadVisits = function() {
        var listVisits;
        return listVisits = new ListVisitsView({
          el: $('#visits-content')[0]
        });
      };

      return ListVisitsPageView;

    })(Backbone.View);
    return ListVisitsPageView;
  });

}).call(this);
