// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "backbone"], function($, Backbone) {
    var VisitModel;
    VisitModel = (function(_super) {

      __extends(VisitModel, _super);

      function VisitModel() {
        return VisitModel.__super__.constructor.apply(this, arguments);
      }

      VisitModel.prototype.attributes = {
        orden: null,
        date_entered: null,
        date_due: null,
        position: null,
        account_name: null,
        account_id: null
      };

      return VisitModel;

    })(Backbone.Model);
    return VisitModel;
  });

}).call(this);
